name: Build signed release APK

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
            RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
            RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
            KEYSTORE_BASE_64: ${{ secrets.KEYSTORE_BASE_64 }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                  distribution: 'zulu'
                  java-version: '17'

            - name: Set up signing key
              run: |
                  base64 -d <<< $KEYSTORE_BASE_64 > release.keystore
                  echo "RELEASE_STORE_FILE=$(realpath release.keystore)" >> $GITHUB_ENV

            - name: Build release APK
              run: ./gradlew assembleRelea

            - name: Upload release APK
              uses: actions/upload-artifact@v2
              with:
                  name: app-release
                  path: ./app/build/outputs/apk/release/app-release.apk
